### ISSUE TITLE
No license or contact info

### ISSUE THREAD

**Issue by MartinBriza** [arkceajin/QtDemos#1]
Hi,
I think this repository is awesome, however I struggle with finding any contact information or under what license terms is your code published. Can you please license your code? 
With how things are now it is really risky to actually use your code in a 3rd party project.
Thanks

**Comment by arkceajin** [comment]
@MartinBriza Thanks remind me to add the license. I add MIT for this repo. so it's free to use.

**Comment by MartinBriza** [comment]
Thanks. However, to completely license your code, a MIT header should be in all the relevant source code files. 

Also, I noticed your profile says you're looking for a job. While I'm not a recruiter, I really think you should include a way to contact you somewhere. :) Listing your email on the internet is not as big of an issue with spam anymore.
